const facilitatorsData= [
  {
    id: '1',
    avatar: '/dp.png',
    fullName: 'James Nwankwo',
    email: 'john@semicolon.africa',
    organizationLogo: '/henleylogo.png',
    course: 'Design Thinking',
    status: 'Active',
    dateAdded: '12 Aug. 2021',
  },
  {
    id: '2',
    avatar: '/dp.png',
    fullName: 'Great Nd',
    email: 'great@semicolon.africa',
    organizationLogo: '/henleylogo.png',
    course: 'Design History',
    status: 'Active',
    dateAdded: '12 Aug. 2021',
  },
  {
    id: '3',
    avatar: '/dp.png',
    fullName: 'Florence Olanike',
    email: 'florence@semicolon.africa',
    organizationLogo: '/semicolonlogo.png',
    course: 'Software Engineering',
    status: 'Pending',
    dateAdded: '12 Aug. 2021',
  },
  {
    id: '4',
    avatar: '/dp.png',
    fullName: 'Joel Onajason',
    email: 'joel@semicolon.africa',
    organizationLogo: '/andela.png',
    course: 'Django Language',
    status: 'Pending',
    dateAdded: '12 Aug. 2021',
  },
  {
    id: '5',
    avatar: '/dp.png',
    fullName: 'Nonso Okoroafor',
    email: 'joel@semicolon.africa',
    organizationLogo: '/henleylogo.png',
    course: 'Java & Springboot',
    status: 'Active',
    dateAdded: '12 Aug. 2021',
  },
];

export default facilitatorsData;